version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pinsaude-postgres
    environment:
      POSTGRES_DB: pinsaude
      POSTGRES_USER: pinsaude_admin
      POSTGRES_PASSWORD: pinsaude_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tools/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pinsaude-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: pinsaude-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  vault:
    image: hashicorp/vault:1.16
    container_name: pinsaude-vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: pinsaude-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: pinsaude-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
