spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinsaude
    username: svc_onboarding
    password: ${DB_PASSWORD_ONBOARDING:local_dev_only}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: onboarding
  flyway:
    schemas: onboarding
    default-schema: onboarding
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pinsaude
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info
