spring:
  config:
    import: "optional:classpath:application-local.yml"
  datasource:
    url: jdbc:postgresql://localhost:5433/pinsaude
    username: svc_faturamento
    password: ${DB_PASSWORD_FATURAMENTO:faturamento_dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: faturamento
  flyway:
    schemas: faturamento
    default-schema: faturamento
    locations: classpath:db/migration
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pinsaude
crypto:
  key: ${CRYPTO_KEY:pinsaude-dev-key-change-in-prod}
receita-federal:
  base-url: ${RECEITA_FEDERAL_URL:https://brasilapi.com.br}
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info
