spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinsaude
    username: svc_gestao
    password: ${DB_PASSWORD_GESTAO:local_dev_only}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: gestao
  flyway:
    schemas: gestao
    default-schema: gestao
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pinsaude
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: health,info
