spring:
  cloud:
    gateway:
      routes:
        - id: fiscal
          uri: http://localhost:8081
          predicates:
            - Path=/api/fiscal/**
        - id: parametros-fiscais
          uri: http://localhost:8081
          predicates:
            - Path=/api/parametros-fiscais/**
        - id: motor-fiscal
          uri: http://localhost:8081
          predicates:
            - Path=/api/motor-fiscal/**
        - id: faturamento
          uri: http://localhost:8082
          predicates:
            - Path=/api/faturamento/**
        - id: tomadores
          uri: http://localhost:8082
          predicates:
            - Path=/api/tomadores/**
        - id: producoes
          uri: http://localhost:8082
          predicates:
            - Path=/api/producoes/**
        - id: servicos
          uri: http://localhost:8082
          predicates:
            - Path=/api/servicos/**
        - id: ledger
          uri: http://localhost:8083
          predicates:
            - Path=/api/ledger/**
        - id: repasse
          uri: http://localhost:8084
          predicates:
            - Path=/api/repasse/**
        - id: onboarding
          uri: http://localhost:8085
          predicates:
            - Path=/api/onboarding/**
        - id: medicos
          uri: http://localhost:8085
          predicates:
            - Path=/api/medicos/**
        - id: empresas
          uri: http://localhost:8085
          predicates:
            - Path=/api/empresas/**
        - id: gestao
          uri: http://localhost:8086
          predicates:
            - Path=/api/gestao/**
        - id: usuarios
          uri: http://localhost:8086
          predicates:
            - Path=/api/usuarios/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pinsaude
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health,info
