spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pinsaude
    username: svc_repasse
    password: ${DB_PASSWORD_REPASSE:repasse_dev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: repasse
  flyway:
    schemas: repasse
    default-schema: repasse
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pinsaude
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health,info
